---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auth
  labels:
    app: vault-auth
data:
  vault.hcl: |-
    storage "file" {
      path = "/tmp/vault/data"
    }

    listener "tcp" {
      address = "0.0.0.0:{{ include "fl.value" (list $ . $.Values.port) }}"
      tls_disable = "true"
      max_request_duration = "120s"
    }

    api_addr = "http://vault-auth:{{ include "fl.value" (list $ . $.Values.port) }}"

    cluster_name = "auth"

    ui = false

    log_level = "debug"
