---
apiVersion: v1
kind: Service
metadata:
  name: vault-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: vault-auth
spec:
  clusterIP: None
  ports:
  - name: auth
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: vault-auth
