---
apiVersion: v1
kind: Service
metadata:
  name: vault-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: vault-auth
spec:
  clusterIP: None
  ports:
  - name: auth
    port: {{ include "fl.value" (list $ . $.Values.port) }}
    protocol: TCP
    targetPort: {{ include "fl.value" (list $ . $.Values.port) }}
  selector:
    app: vault-auth
