---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: vault-auth
spec:
  replicas: 3
  serviceName: vault-auth
  selector:
    matchLabels:
      app: vault-auth
  template:
    metadata:
      labels:
        app: vault-auth
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: vault-auth
          image: {{ .Values.werf.image.vault }}
          command: [ 'vault', 'server', '-config', '/etc/vault.hcl' ]
          ports:
          - name: auth
            containerPort: {{ include "fl.value" (list $ . $.Values.port) }}
            protocol: TCP
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          env:
            - name: VAULT_LOG_LEVEL
              value: debug
          volumeMounts:
            - name: config
              mountPath: /etc/vault.hcl
              subPath: vault.hcl
              readOnly: true
      volumes:
      - name: config
        configMap:
          name: vault-auth
          defaultMode: 0644
