#!/bin/sh

set -x
set -e

echo flant_gitops.sh BEGIN
echo VAULT_ADDR="${VAULT_ADDR}"
echo VAULT_CACERT="${VAULT_CACERT}"
echo VAULT_TLS_SERVER_NAME="${VAULT_TLS_SERVER_NAME}"
echo VAULT_REQUEST_TOKEN_GET_CONFIGURATION="${VAULT_REQUEST_TOKEN_GET_CONFIGURATION}"
echo
echo VAULT_CACERT BEGIN
cat $VAULT_CACERT
echo VAULT_CACERT END
echo
echo root | vault login -
echo VAULT_REQUEST_TOKEN_GET_CONFIGURATION UNWRAP BEGIN
vault write -format=json sys/wrapping/unwrap token="${VAULT_REQUEST_TOKEN_GET_CONFIGURATION}"
echo VAULT_REQUEST_TOKEN_GET_CONFIGURATION UNWRAP end
echo flant_gitops.sh END
