#!/bin/sh

echo flant_gitops.sh BEGIN
echo VAULT_ADDR="${VAULT_ADDR}"
echo VAULT_CACERT="${VAULT_CACERT}"
echo VAULT_TLS_SERVER_NAME="${VAULT_TLS_SERVER_NAME}"
echo VAULT_REQUEST_TOKEN_GET_CONFIGURATION="${VAULT_REQUEST_TOKEN_GET_CONFIGURATION}"
echo flant_gitops.sh END
