version: "3"

services:
  vault:
    container_name: vault
#    image: vault:1.7.1
    image: tetafro/golang-gcc:1.16-alpine
    volumes:
      - "../vault-plugins/build/:/vault/plugins"
    ports:
      - 8200:8200
    privileged: true
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=root
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_LOG_LEVEL=debug

      - VAULT_CLIENT_TIMEOUT=120s
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_LOG_FORMAT=json
    command: /bin/vault server -dev -dev-plugin-dir=/vault/plugins
    cap_add:
      - IPC_LOCK
    depends_on:
      - kafka


  test-client:
    container_name: test-client
    build:
      context: .
      dockerfile: Dockerfile.test-client
    volumes:
      - "../authd/build:/opt/authd/bin"
      - "../cli/build:/opt/cli/bin"
    command: sleep infinity
    depends_on:
      - vault

  test-server:
    container_name: test-server
    build:
      context: .
      dockerfile: Dockerfile.test-server
    volumes:
      - "../authd/build:/opt/authd/bin"
      - "../server-access/flant-server-accessd/build:/opt/server-access/bin"
      - "../server-access/server-access-nss/build/libnss_flantauth.so.2:/lib/x86_64-linux-gnu/libnss_flantauth.so.2"
    environment:
      - SERVER_ACCESSD_CONF=/opt/server-access/config.yaml
    depends_on:
      - vault

networks:
  default:
    name: negentropy
