---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-root
  namespace: {{ .Values.namespace }}
  labels:
    app: vault-root
spec:
  replicas: 1
  serviceName: vault-root
  selector:
    matchLabels:
      app: vault-root
  template:
    metadata:
      labels:
        app: vault-root
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: vault-root
          image: {{ .Values.werf.image.vault }}
          command: [ 'vault', 'server', '-config', '/etc/vault.hcl' ]
          ports:
          - name: root
            containerPort: {{ pluck .Values.werf.env .Values.port | first | default .Values.port._default }}
            protocol: TCP
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          env:
            - name: VAULT_LOG_LEVEL
              value: debug
          volumeMounts:
            - name: config
              mountPath: /etc/vault.hcl
              subPath: vault.hcl
              readOnly: true
      volumes:
      - name: config
        configMap:
          name: vault-root
          defaultMode: 0644
