{{- include "globals" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "werf/watch-logs": "true"
spec:
  activeDeadlineSeconds: 360
  backoffLimit: 1
  template:
    metadata:
      name: {{ .Chart.Name }}-migrate
    spec:
      restartPolicy: Never
      containers:
      - image: {{ .Values.werf.image.migrations }}
        name: migration
        command:
        - bash
        - -c
        - |
          repeat=1; while  [ $repeat -ne 0 ] ; do result=$(curl -sf http://vault-root:8200/v1/sys/init ); repeat=$? ; sleep 1; done;
          if [ "$(echo "$result" | jq -r .initialized)" == "false" ] ; then 
            python3 scripts/start.py --mode=kube;
          else
            echo "Already initialized"
          fi
        env:
{{- include "vault.env" . | nindent 10 }}
        volumeMounts:
        - name: migration
          mountPath: /app/infra/common/config/environments
      volumes:
      - name: migration
        configMap:
          name: migration
