{{- include "globals" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Chart.Name }}-migrate
  name: {{ .Chart.Name }}-migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "werf/watch-logs": "true"
spec:
  activeDeadlineSeconds: 360
  backoffLimit: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-migrate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-migrate
    spec:
      restartPolicy: Never
      containers:
      - image: {{ .Values.werf.image.migrations }}
        name: migration
        command:
        - sh
        - -c
        - python3 scripts/start.py --mode=kube
        env:
{{- include "vault.env" . | nindent 10 }}
        volumeMounts:
        - name: migration
          mountPath: /app/infra/common/config/environments
      volumes:
      - name: migration
        configMap:
          name: migration
