{{- include "globals" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-python-migrations
  name: {{ .Chart.Name }}-python-migrations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-python-migrations
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-python-migrations
    spec:
      containers:
      - image: {{ .Values.werf.image.migrations }}
        name: migration
        command:
        - sleep
        - "10000"
        env:
{{- include "vault.env" . | nindent 10 }}
        volumeMounts:
        - name: migration
          mountPath: /app/infra/common/config/environments/kube.yaml
      volumes:
      - name: migration
        configMap:
          name: migration
