---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy
subjects:
- kind: ServiceAccount
  name: deploy
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitops
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","read","get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops
subjects:
- kind: ServiceAccount
  name: gitops
  namespace: {{ .Release.Namespace }}
