{{- $vault_port := pluck .Values.werf.env .Values.vault_port | first | default .Values.vault_port._default }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-auth
  labels:
    app: vault-auth
spec:
  replicas: 3
  serviceName: vault-auth
  selector:
    matchLabels:
      app: vault-auth
  template:
    metadata:
      labels:
        app: vault-auth
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: vault-auth
          image: {{ .Values.werf.image.vault }}
          command: [ 'vault', 'server', '-config', '/etc/vault.hcl' ]
          ports:
          - name: auth
            containerPort: {{ $vault_port }}
            protocol: TCP
          securityContext:
{{- include "vault.securitycontext" . | nindent 12 }}
          env:
{{- include "vault.env" . | nindent 10 }}
          volumeMounts:
            - name: config
              mountPath: /etc/vault.hcl
              subPath: vault.hcl
              readOnly: true
      volumes:
      - name: config
        configMap:
          name: vault-auth
          defaultMode: 0644
---
apiVersion: v1
kind: Service
metadata:
  name: vault-auth
  labels:
    app: vault-auth
spec:
  clusterIP: None
  ports:
  - name: auth
    port: {{ $vault_port }}
    protocol: TCP
    targetPort: {{ $vault_port }}
  selector:
    app: vault-auth
