---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-init
data:
  init.sh: |
    #!/bin/bash

    cd /tmp
    cat /etc/vault.hcl | sed 's/0.0.0.0:/127.0.0.1:/g' > /tmp/vault.hcl
    vault server -config /tmp/vault.hcl > /tmp/vault.log 2>&1 &
    vault=$!
    echo "Wait vault for check status"
    while ! curl -s $VAULT_ADDR/v1/sys/seal-status --connect-timeout 1 ; do
      sleep 2
    done
    if [ "$(vault status -format=json | jq -r .initialized)" = "false" ]; then
      until curl -sf http://vault-conf:8200/v1/vault-cert-auth/ca/pem -o vault-conf-ca.pem ; do
        echo "Retrieving CA"
        sleep 2
      done
      KEYFILE="$(hostname)-recovery-keys-encrypted.txt"
      vault_recovery_pgp_keys="$(find "/etc/recovery-pgp-keys/" -type f | tr '\n' ',' | sed 's/,$//g')"
      recovery_shares="$(ls /etc/recovery-pgp-keys | wc -l)"
      recovery_threshold="${recovery_shares}"
      vault_init_out="$(vault operator init -recovery-shares="${recovery_shares}"  -recovery-threshold="${recovery_threshold}" -recovery-pgp-keys="${vault_recovery_pgp_keys}")"
      export VAULT_TOKEN=$(echo "$vault_init_out" | grep "^Initial Root Token: " | awk '{print $4}')
      echo "$vault_init_out" | grep "^Recovery Key " | awk '{print $4}' > "$KEYFILE"
      vault auth enable cert
      vault write auth/cert/certs/cert-auth display_name='cert-auth' policies='cert-auth' certificate=@vault-conf-ca.pem ttl='3600'
      echo 'path "*" {capabilities = ["create", "read", "update", "delete", "list", "sudo"]}' | vault policy write cert-auth -
      vault token revoke -self
      until gsutil cp "$KEYFILE" gs://${BUCKET}/ ; do
       sleep 2
      done
    fi
    kill $vault
    wait $vault
