{{- include "globals" . }}
{{- $vault_name := "vault-conf" -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $vault_name }}
  labels:
    app: {{ $vault_name }}
spec:
{{ if (.vault_ha) }}
  replicas: 3
{{ else }}
  replicas: 1
{{ end }}
  serviceName: {{ $vault_name }}
  selector:
    matchLabels:
      app: {{ $vault_name }}
  template:
    metadata:
      labels:
        app: {{ $vault_name }}
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: gitops
      initContainers:
        - name: init
          image: {{ pluck "vault-init" .Values.werf.image | first }}
          command: ["/init.sh"]
          securityContext:
{{- include "vault.securitycontext" . | nindent 12 }}
          env:
{{- include "vault.env" . | nindent 10 }}
          envFrom:
            -  configMapRef:
                name: bootstrap
          volumeMounts:
{{- include "vault.volumemounts" . | nindent 10 }}
          - mountPath: /vault/userconfig/tls
            name: {{ $vault_name }}-tls
            readOnly: true
          - mountPath: /init.sh
            name: init
            subPath: init.sh
            readOnly: true
      containers:
        - name: {{ $vault_name }}
          image: {{ .Values.werf.image.vault }}
          command: [ 'vault', 'server', '-config', '/etc/vault.hcl' ]
          ports:
          - name: tcp
            containerPort: {{ .vault_port }}
            protocol: TCP
          - name: cluster
            containerPort: {{ .vault_cluster_port }}
            protocol: TCP
          securityContext:
{{- include "vault.securitycontext" . | nindent 12 }}
          env:
{{- include "vault.env" . | nindent 10 }}
{{- include "vault.lifecycle" . | nindent 10 }}
{{- include "vault.probes" . | nindent 10 }}
          volumeMounts:
{{- include "vault.volumemounts" . | nindent 10 }}
{{- include "vault.kafka.volumemounts" . | nindent 10 }}
          - mountPath: /vault/userconfig/tls
            name: {{ $vault_name }}-tls
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ $vault_name }}
          defaultMode: 0644
      - name: init
        configMap:
          name: vault-conf-init
          defaultMode: 0755
      - name: {{ $vault_name }}-tls
        secret:
          defaultMode: 420
          secretName: {{ $vault_name }}-tls
{{- include "kafka.secret.volumes" . | nindent 6 }}
{{- include "vault.volumeclaimtemplate" . | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $vault_name }}
  labels:
    app: {{ $vault_name }}
spec:
  ports:
  - name: tcp
    port: {{ .vault_port }}
    protocol: TCP
    targetPort: {{ .vault_port }}
  - name: cluster
    port: {{ .vault_cluster_port }}
    protocol: TCP
    targetPort: {{ .vault_cluster_port }}
  selector:
    app: {{ $vault_name }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $vault_name }}
spec:
  secretName: {{ $vault_name }}-tls
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  commonName: {{ $vault_name }}
  dnsNames:
  - {{ $vault_name }}
{{ if (.vault_ha) }}
{{ range $i,$e := until 3 }}
  - {{ printf "%s-$i.%s.%s.svc.cluster.local" $vault_name $vault_name .Values.werf.namespace }}
{{ end }}
{{ else }}
  - {{ printf "%s-0.%s.%s.svc.cluster.local" $vault_name $vault_name .Values.werf.namespace }}
{{ end }}
  - {{ printf "%s.%s.svc.cluster.local" $vault_name .Values.werf.namespace }}
  {{- if .Values.domain -}}
  {{- $domain := pluck .Values.werf.env .Values.domain | first | default false }}
  {{- if $domain }}
  - {{ printf "%s.%s" $vault_name $domain }}
  {{- end }}
  {{- end }}
  ipAddresses:
  - 127.0.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $vault_name }}
  labels:
    app: {{ $vault_name }}
data:
  vault.hcl: |-
{{ if (.vault_ha) }}
    storage "raft" {
{{ else }}
    storage "file" {
{{ end }}
      path = {{ .vault_data_path | quote }}
    }
    listener "tcp" {
      address = "0.0.0.0:{{ .vault_port }}"
      cluster_address = "0.0.0.0:{{ .vault_cluster_port }}"
      tls_cert_file = "/vault/userconfig/tls/tls.crt"
      tls_key_file  = "/vault/userconfig/tls/tls.key"
      tls_disable = false
      max_request_duration = "120s"
    }
    disable_mlock = true
    cluster_name = "conf"
{{ if (.vault_ha) }}
    service_registration "kubernetes"
{{ end }}
    ui = false
