{{- include "globals" . }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-auth
  labels:
    app: vault-auth
spec:
  replicas: 1
  serviceName: vault-auth
  selector:
    matchLabels:
      app: vault-auth
  template:
    metadata:
      labels:
        app: vault-auth
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: vault-auth
          image: {{ .Values.werf.image.vault }}
          command: [ 'vault', 'server', '-config', '/etc/vault.hcl' ]
          ports:
          - name: tcp
            containerPort: {{ .vault_port }}
            protocol: TCP
          securityContext:
{{- include "vault.securitycontext" . | nindent 12 }}
          env:
{{- include "vault.env" . | nindent 10 }}
{{- include "vault.lifecycle" . | nindent 10 }}
          volumeMounts:
{{- include "vault.volumemounts" . | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: vault-auth
          defaultMode: 0644
{{- include "vault.volumes" . | nindent 6 }}
{{- include "vault.volumeclaimtemplate" . | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: vault-auth
  labels:
    app: vault-auth
spec:
  ports:
  - name: tcp
    port: {{ .vault_port }}
    protocol: TCP
    targetPort: {{ .vault_port }}
  selector:
    app: vault-auth
