---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-init
data:
  init.sh: |
    #!/bin/bash

    cd /tmp
    until [ -f "ca.pem" ]; do
      echo "Retrieving CA"
      gsutil cp gs://${BUCKET}/ca.pem .
      sleep 2
    done
    cat /etc/vault.hcl | sed 's/0.0.0.0:/127.0.0.1:/g' > /tmp/vault.hcl
    vault server -config /tmp/vault.hcl &
    if [ "$(vault status -format=json | jq -r .initialized)" = "false" ]; then
      KEYFILE="$(hostname)-recovery-keys-encrypted.txt"
      vault_init_out="$(vault operator init -recovery-shares=1  -recovery-threshold=1 -recovery-pgp-keys="/etc/recovery-pgp-keys/carol-pub-key.asc")"
      export VAULT_TOKEN=$(echo "$vault_init_out" | grep "^Initial Root Token: " | awk '{print $4}')
      echo "$vault_init_out" | grep "^Recovery Key " | awk '{print $4}' > "$KEYFILE"
      cat "$KEYFILE"
      until gsutil cp "$KEYFILE" gs://${BUCKET}/ ; do
       sleep 2
      done
    fi
