apiVersion: v1
kind: AuthdConfig
jwtPath: "./dev/secret/authd.jwt"
defaultSocketDirectory: "./dev/run"
servers:
  - domain: root-source.negentropy.example.com
  - domain: auth.negentropy.example.com
    default: true
  - domain: "*.auth.negentropy.example.com"
  - #type: auth
  #    domain: "https://localhost:8200"
  - type: auth
    domain: "https://localhost:8200"
