apiVersion: v1
kind: AuthdConfig
jwtPath: "./dev/secret/authd.jwt"
defaultSocketDirectory: "./dev/run"
servers:
  - domain: root-source.negentropy.example.com
  - domain: auth.negentropy.eample.com
    default: true
  - domain: "*.auth.negentropy.example.com"
  - type: auth
    domain: "127.0.0.1:8200"
