name: Flant IAM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
    defaults:
      run:
        shell: bash
        working-directory: vault-plugins/flant_iam/tests

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Check out pull request's HEAD commit instead of the merge commit to
          # work-around an issue where wrong a commit is being checked out.
          # For more details, see:
          # https://github.com/actions/checkout/issues/299.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build
        run: make build
        working-directory: vault-plugins/flant_iam

      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Setup Vault
        run: bash start.sh --ci-mode

      - name: Tests
        run: yarn && yarn test
