name: Flant IAM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
    defaults:
      run:
        shell: bash
        working-directory: vault-plugins/flant_iam/tests

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build && sudo chown -R 100:1000 build/
        working-directory: vault-plugins/flant_iam

      - name: Run vault
        run: bash start.sh --ci-mode

      - name: Tests
        run: yarn && yarn test

      - name: Cleanup
        if: ${{ always() }}
        run: |
          docker stop dev-vault || true
          docker rm dev-vault || true
