name: Watcher

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rego:
    name: Watcher
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Check out pull request's HEAD commit instead of the merge commit to
          # work-around an issue where wrong a commit is being checked out.
          # For more details, see:
          # https://github.com/actions/checkout/issues/299.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install golang-ci lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.38.0

      - name: Lint Watcher
        working-directory: rolebinding-watcher
        run: ${GITHUB_WORKSPACE}/bin/golangci-lint --version; ${GITHUB_WORKSPACE}/bin/golangci-lint run ./... --config ../vault-plugins/.golangci.yaml

      - name: Test ${{ matrix.plugin }}
        working-directory: rolebinding-watcher
        run: go test -race -vet=off ./...
