name: Build and Deploy

on:
  workflow_dispatch:
    branches:
      - main
      - kubernetization

jobs:
  deploy_production:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Werf converge
        uses: werf/actions/converge@v1.2
        with:
          channel: beta
          env: dev
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
